Fix/redundant sim params
rl-institut/smooth pull request #209
Opened 2020-10-29 12:27 UTC by j-ti

2020-11-30 10:31 UTC, stefansc1 requested changes

2020-11-30 10:31 UTC, stefansc1 commented on smooth/components/component_electrolyzer_waste_heat.py
> +        Electrolyzer.update_flows(self, results, self.name)
Can be simplified to `Electrolyzer.update_flows(self, results)`
self.name is default when name is omitted.

2020-11-30 10:31 UTC, stefansc1 commented on smooth/components/component_electrolyzer_waste_heat.py
> +            self, results, self.sim_params, self.name + "_thermal"
Bug: Electrolyzer has no `update_flows`, so `Component.update_flows` is used. But this has no sim_params parameter any more.
Fix: `Electrolyzer.update_flows(self, results, self.name + "_thermal")`

Please check with a model that contains a waste heat electrolyzer.

2021-01-13 21:41 UTC, j-ti commented
Closed in favor of updated PR #228

2021-01-13 21:41 UTC, closed without merging