Update of economics of scale
rl-institut/smooth pull request #210
Opened 2020-11-02 16:53 UTC by j-brendel

This is an update of the function.

It now includes checks for 
- increment: the dicts have to be given in ascending order of thresholds
- overlap: An overlapping definition of dicts is not allowed
- and positive intervals: low_thershold < high_threshold

The keyword 'variable' can now be used for CAPEX, OPEX, FIX_EMISSIONS and OP_EMISSIONS

The function 'choose_valid_dict' was implemented as function in smooth/framework/functions/functions.py as it is called several times.

I added a zip file that contains an example model to demonstrate the use.

[examples_economics_of_scale.zip](https://github.com/rl-institut/smooth/files/5476551/examples_economics_of_scale.zip)

2020-11-26 14:38 UTC, ciaradunks approved these changes

2020-11-30 10:08 UTC, stefansc1 requested changes

2020-11-30 10:08 UTC, stefansc1 commented on smooth/framework/functions/functions.py
> +    :return: Valid dictionary (capex/fix_emissions) for the actual value of the depending parameter of the component
Line is too long.

2020-11-30 10:08 UTC, stefansc1 commented on smooth/framework/functions/update_annuities.py
> +        # Check if 'variable' op_emissions are beeing used, if so decide which op_emissions are valid
Line is too long. Fix the spelling error (beeing -> being), then it should fit. Check with flake8.

2020-11-30 12:01 UTC, stefansc1 approved these changes

2020-11-30 12:03 UTC, merged